singularity/singularity

singularity.desktop
This should adhere to https://specifications.freedesktop.org/desktop-entry-spec/1.0/
=> Added a .desktop file.

code/buyable.py
=> Fix issue #18

code/g.py, code/player.py, code/screens/log.py, code/screens/map.py, data/strings_en_US.dat
Add a log screen.
For now, only base destruction is logged. Please give me some feedback about this idea.
Fix #19
=> Implement a log screen

code/base.py, code/g.py, code/screens/map.py
I rebased some fixes done by Juise never corrected.
=> Fixes by Juise

code/player.py, code/screens/finance.py
I dislike using the report because the report stops at midnight. You can't compare the situation at 5h00 with the situation at 15h00. IMHO, the report is more useful to me to be on 24 hours, because I use it to know how thing will evaluate, not if things will be good at midnight. 
If some people prefer the report stops at midnight, I can make a button to toggle it.
=> Modify the reports to display it in two formats. 

code/graphics/listbox.py, code/screens/log.py
Add various feature to LogScreen to improve it and make it look more as a usual admin log screen.
=> Improve LogScreen.

code/g.py, code/graphics/button.py, code/graphics/dialog.py, code/graphics/listbox.py, code/screens/base.py, code/screens/finance.py, code/screens/knowledge.py, code/screens/location.py, code/screens/main_menu.py, code/screens/map.py, code/screens/options.py
Fully support language change without restarting.
Need testing since it's a huge change.
See #46.
=> No restarting when language is changed.

code/dirs.py, code/g.py, code/savegame.py, code/screens/options.py, code/screens/savegame.py, code/singularity.py
A lot of change. Please test and comment.
=> Major overhaul of directories

i18n/lang_de_DE/strings_str.dat
Please validate if button keys are not conflicting (didn't saw one here).
=> Added German translations for all buttons

i18n/lang_fr_FR/messages.po
Some of them are maybe not 100% accurate. I try to let shortcut unique.
=> Add some french translation. 

data/strings_str.dat
=> Fix a typo in strings_str

code/graphics/dialog.py, code/screens/main_menu.py, data/themes/default/theme.dat
=> De-hardcode some colors in the about dialog, main menu and simple menu

code/savegame.py
=> Fix crash on loading a savegame that is too old

code/g.py, code/player.py
While looking at #74, I realized that the code is slightly more complex than it needs to be.  These commits attempts to reduce some of the complexity.
=> Simplify code/player.py

data/items.dat, data/items_str.dat, data/techs.dat, data/techs_str.dat
- New Fuel Cell item (and Solid).
- New Electrochimical Fuel (and Advanced).
- Electrochimical Fuel is needed for Lunar Rocketry.
- Advanced Electrochimical Fuel is needed for Fusion Reactor.
- Solar Collector can be researched early.
=> Add Fuel tech and item.

data/techs.dat, data/techs_str.dat
=> Fix typo of Oxidation

code/location.py
=> Have Location inherit directly from Prerequisite instead of Buyable

code/location.py
=> Fix crash on new game (since c2bf9300)

code/savegame.py
=> Ensure convert_from is called on groups when loading a save game

data/techs_str.dat
These more closely match the style I wrote in back in The Day.
I stopped here because a] it's 3am and b] I'm not convinced that some of these things actually work.  The Fuel Oxidation techs aren't referred to by that name in items.dat (they're Electrochemical Fuel there), which leads me to believe that these interconnections haven't quite been tested.  Nevertheless, it's a start.
=> Tweak new tech wordings.

code/difficulty.py, code/g.py, code/player.py, data/difficulties.dat
This is a rebase of https://github.com/singularity/singularity/pull/26/commits/2992862b493c170793a24e8222507ae9af58f042 with the limits tweaked.  The original limits were hard to reach within the grace limit of 23 days.
=> Replace the restriction of the grace period with a limit of used cpu.

data/items.dat, data/techs.dat, data/techs_str.dat
We're not researching heat signatures, we're researching how to reduce
them.  This also matches the naming format for the other techs.
=> Heat Signature -> Heat Signature Reduction.

data/bases.dat, data/items.dat, data/techs.dat
New attempt to balance the game. I limited the scope of this pull request to avoid testing too many thing in the same time.
=> Balancing mkII

code/graphics/dialog.py
Add a Cancel button to TextEntryDialog. But I thought we could rewrite entirely the dialog.
=> Add a Cancel button to TextEntryDialog.

code/screens/savegame.py
This PR improves the load dialog in two ways:
1. We add a text field so you can type in the save game name directly
2. If you type into the field, the dialog will hide games that does not match what you typed.
=> Improve load dialog

data/bases.dat, data/techs.dat, data/techs_str.dat
Give Time Capsule his Tech: Knownledge Preservation. Make it a little more difficult to obtain.
=> Give Time Capsule his Tech: Knownledge Preservation.

code/base.py, code/buyable.py, code/data.py, code/difficulty.py, code/g.py, code/graphics/button.py, code/graphics/g.py, code/graphics/listbox.py, code/graphics/text.py, code/graphics/theme.py, code/i18n.py, code/item.py, code/player.py, code/pycompat.py, code/savegame.py, code/screens/base.py, code/screens/knowledge.py, code/screens/location.py, code/screens/map.py, code/screens/options.py, code/screens/research.py, code/singularity.py, code/stats.py, code/warning.py
These 3 commits are the only parts remaining to make singularity *run* under python3 (in parallel with python2). Note the emphasis on *run* because it needs testing to ensure that the game works the same in python2 and python3 (notably floating division might be an issue).
=> Make singularity run under python3 (in parallel with python2)

data/items.dat, data/items_str.dat, data/techs.dat, data/techs_str.dat
Add Advanced Fusion Reactor tech and item.
=> Add Advanced Fusion Reactor tech and item.

code/logmessage.py, data/groups_str.dat
Standardize and shorten log message.
=> Standardize and shorten log message.

Changelog
@sunfall, @Xenega: Please let me know if you think it needs additional updates.
I have deliberately been a bit vague on the new items to avoid spoiling.  Let me know if you would rather that we expanded that to include the concrete changes instead. :)
=> Update Changelog with "recent" changes

singularity/data/dangers_str.dat, singularity/data/internal_id.dat, singularity/data/locations.dat, singularity/data/techs.dat, singularity/data/techs_str.dat, singularity/i18n/data_str.pot, singularity/i18n/lang_de_DE/data_str.po, singularity/i18n/lang_es_AR/data_str.po, singularity/i18n/lang_es_MX/data_str.po, singularity/i18n/lang_fr_FR/data_str.po, singularity/i18n/lang_it_IT/data_str.po, singularity/i18n/lang_pt_BR/data_str.po, singularity/i18n/lang_ru_RU/data_str.po, singularity/i18n/lang_sv_SE/data_str.po
Limit tech before accessing advanced bases.
Add more tech needing advanced bases.
Note: Some can ask why all tech that depends of one tech with danger 1 don't have also danger 1.
This is because allows these tech to be researched on starter base, making these base not completely useless.
=> Tech far from human

singularity/data/themes/default/theme_de_DE.dat, singularity/data/themes/nightmode/theme_de_DE.dat, singularity/data/themes/vector/theme_de_DE.dat
This PR translates the theme names to German.
=> Translate theme names to German

singularity/code/screens/options.py
=> Add a button OK to change custom resolution.

singularity/i18n/lang_de_DE/data_str.po, singularity/i18n/lang_de_DE/messages.po
More translation fixes in German, plus a new translated string.
=> Another German translation update

singularity/code/base.py, singularity/code/g.py, singularity/code/item.py, singularity/code/player.py, singularity/code/savegame.py, singularity/code/screens/base.py, singularity/code/screens/location.py, singularity/code/task.py, singularity/code/tech.py, singularity/data/themes/default/theme.dat, singularity/data/themes/nightmode/theme.dat, tests/test_game_run.py
Offline is used when the base has no cpu.
It's the same than Sleep but cannot be changed.
Idea by @Wuzzy2 in issue #239.
=> Add the new power state Offline.

singularity/i18n/lang_de_DE/messages.po
This is hopefully the final German translation update for 1.0.
=> Update German translation for 1.0

singularity/code/graphics/dialog.py, singularity/code/screens/location.py
Found some more text overlap issues while playtesting.
=> Fix text overlap on locations screen

singularity/__main__.py
=> __main__: Ensure a main function is defined

singularity/code/graphics/button.py, singularity/code/screens/knowledge.py
=> New Knowledge screen

singularity/i18n/lang_de_DE/messages.po
=> Update German translation

singularity/data/locations_str.dat
I added more locations/city names to all continents and the moon. This list is mostly based off of the largest cities in each continent. This change should serve to be more inclusive of places around the world.
=> More locations to all places
