singularity/singularity

code/player.py
You forgot to adjust secs_passed correctly after throttling time per tick. This bug might be related to this issue https://github.com/singularity/singularity/issues/18, but I'm not sure.
=> Fix time throttler miscalculating secs_passed

code/screens/location.py
Display the completion and the time before completion of the building CPU in the location screen.
=> Add information about CPU completion percentage and time

code/screens/map.py, code/screens/warning.py, data/strings_en_US.dat
Warning list:
* DONE => All cpu are not used
* DONE => Only one base left
* TODO => Not enough cash to build (#21)
Improvements:
* TODO => Display only one time a warning if player said continue except if situation change
* DONE => Display one dialog with multiple warning  
* TODO => Warning list screen
Don't hesitate to propose new warning.
This pull request can be merged partially. No commit depends of a later commit.
=> Display warning to players

code/difficulty.py, code/g.py, code/player.py, data/difficulties.dat
It shouldn't change the chance per day to lost, but reduce cost of discovering (less discover = less base to rebuilt). Since discover cost is mostly relevant at the beginning, it is not a real problem, but something good (since now the beginning is hard but the end is easier).
Basically, Expected value (lost) = discover_chance * suspicion_value
So, we rise suspicion_value, we can reduce discover_chance. Before suspicion_value was constant.
Very Easy = 7000 * 10000 = 8750 * 8000              
Easy = 9000 * 10000 =~ 9500 * 9500                   
Hard = 11000 * 10000 =~ 10500 *10500         
Very-Hard = 13000 * 10000 =~ 11250 * 11500     
Impossible = 15000 * 10000 = 12000 * 12500
(not all expected value are exactly equals)
=> Add suspicion multiplier and reduce discover multiplier

code/savegame.py
While testing save games in my "improve-loggning-branch", I noticed the load function crashing on recent saved games due to new classes being used.  This branch makes save games created from the master branch loadable again.
=> Fix crash on ItemType and OrderedDict when loading save game

TODO, code/graphics/dialog.py, code/graphics/listbox.py, code/screens/location.py, code/screens/savegame.py
This branch makes two user visible improvements to the double-handling of listbox-based dialogs:
* Double-clicking on an item in the "Location" menu menu now acts as "Open Base"
* Double-click handling now *only* triggers if you double-click on an actual (and not just an "empty" row in the listbox)
Internally, we also centralize the double-click handling in the listbox widget to ensure the behaviour is consistent across all listbox-based dialogs reacting to double-clicking.
=> Improve double-clicking on items in listbox dialogs

data/bases.dat, data/techs.dat, data/techs_str.dat
The former construction feels both like clumsy English and has an
unfortunate rhythm thing going that's a bit distracting.  This also
fixes the display name for Advanced C.I., which was still just CI
(presumably a cut-and-paste error).
=> Corporation Identification -> Corporate Identification (plus a display name fix)

code/data.py, code/g.py, code/location.py, code/player.py, code/savegame.py, code/screens/map.py
This splits Location into a stateful part (still called Location) and
spec.  The stateful part is moved to the player object and all
references to it is updated to follow.
=> Split Location into a stateful part and LocationSpec

data/events_str.dat, data/items_str.dat, data/techs_str.dat
These now match the old style more closely. A not-actual-typographic fix was reverted in events_str.dat as well.  The bits about discovery reduction for the Fuel Cells was removed, as they don't actually have that effect, and a warning that researching Advanced Oxidation is dangerous was added to the research description.
=> Further update new strings.

code/graphics/g.py
Mitigates #156 by only loading the font sizes we need as we need them.
With this, we go from loading 200 instances of Font to less than 70
at the start of the game.
=> Reduce file descriptor usage due to fonts

code/logmessage.py, code/player.py, code/savegame.py, code/screens/log.py
With this branch, it will be possible to re-read messages (in full) via the log menu by double clicking on the log line.
Known issues:
=> Support re-opening (some) messages in full via the log menu

code/g.py, code/graphics/dialog.py, code/player.py, code/screens/base.py, code/screens/location.py, code/screens/map.py
This PR will change the "additional information" values in the cash display and CPU display (i.e. the numbers in brackets).
Previously, we used for:
* cash: `Current cash - total price of all (active) buyables`
* CPU: `Size of (effective) CPU pool`
With this change, they are now:'
* cash: `Expected cash flow within the next hour`.  If it is positive, the player is earning money, if negative, the player is losing money. 
* CPU: `How many CPUs are idle/missing in the CPU pool`.  If positive, this is the (average) number of CPU units will be performing jobs.  If negative, this the average number of CPU units missing to satisfy the current needs.
Known omissions to the cash view: Income from interest rates and `Arbitrage`.  This is by design to avoid giving the player false hope the hour up …
=> Display current cash / CPU flow in the map view

code/screens/location.py
Fixes a regression from 5ff71b1. When the sleep/active state of a base changed, the available CPU didn't update immediately. This looks like the logical place to add it if 5ff71b1 is correct, though unless MapScreen.rebuild is called on every frame it's worth considering whether the computational cost is so bad compared with the extra lines of code and opportunity for error.
Linked to issue [179](https://github.com/singularity/singularity/issues/179).
=> Recalculate CPU availability after changing sleep/wake state of a base

code/screens/base.py
Fix breakage of the game due to an incorrect form of check for None that does not take into account that 0 is also evaluated as False
=> Fix breakage of base construction

code/player.py, code/screens/map.py, code/screens/report.py, code/stats.py
Based on issue #74, I have rewritten the financial reports deal with resource flow (rather than how much money you will have in 24 hours) and used `compute_future_resource_flow` to compute these numbers.  This should make the reports more reliable for determining what you spend your resources (see #74 for some of the issues @PeterJust found) plus it also gives us insight into `compute_future_resource_flow` and enables us to debug that easier.
Given this was the last use of the `dry_run=True` paths in `pl.give_time`, I also remove that in a separate commit.  This amounts to about 33% reduction of the code (300+ lines to ~220 lines).
cc: @PeterJust
=> Rewrite financial reports 

singularity/__init__.py, singularity/code/graphics/button.py, singularity/code/graphics/g.py, singularity/code/graphics/text.py, singularity/code/screens/map.py, singularity/code/screens/options.py, singularity/code/screens/report.py
I believe this will fix #200.  With this patch, the story mode dialogs (among other) uses a consist font-size for me.
@evilmrhenry / @Xenega: If you have time, it would be great if you could review this change.  Note I have deliberately skipped the Options widget to control text-sizes via the Options menu for now. If we merge this, I will file an issue to follow up on that later.
=> Make (some) text sizes configurable and reduce the default size

singularity/code/screens/map.py, singularity/data/themes/default/theme.dat, singularity/data/themes/nightmode/theme.dat
Give the player a quick insight into their bases and their status.
We show 3 numbers for the player:
* The number of active bases (that can sustain the singularity)
* The total number of bases (all inclusive)
* In brackets, the number of bases *not* able to maintain the
singularity and also *not* under construction/building items.
The display has color codes to make the player aware of the following
conditions (in order):
* Only one active base left (default "red")
* Idle bases that cannot sustain the singularity (default "yellow")
* Too many bases in total (default "orange")
* Otherwise everything ok (default "white")
=> Add a base overview to the info screen

singularity/code/screens/report.py, singularity/code/screens/stat.py
* Fix text overlap on reports screen
* Large numbers on stats screen towards the end game become small, so I made that a bit wider too.
Screenshot of the overlap (gd locale):
Screenshot with this branch:
=> Make report and stats screens wider

singularity/code/screens/options.py
Bigger Resolution OK button, more room for menu tabs texts and consistent alignment.
The OK button text is too small in the GD locale ad the text is too hard to read:
So I had to make the button wider. English screenshot with this branch:
=> Tweak Options screen layout

singularity/code/screens/base.py, singularity/code/screens/location.py
Fix text overlap and too tiny text on locations screen in gd locale by making it wider. Make base screen wider to match.
Before:
After:
And the wider base screen:
=> Make location and base screens wider to fit more text

singularity/code/graphics/dialog.py
Redesign textentry dialog with buttons on the bottom to fit more text in them.
Usage: Menu -> Save Game; Location -> Rename Base
Screenshot of the problem with gd locale:
Screenshot with this branch:
=> Redesign textentry with buttons on the bottom

singularity/code/graphics/dialog.py, singularity/code/screens/location.py, singularity/code/screens/savegame.py, singularity/data/themes/default/theme.dat, singularity/data/themes/nightmode/theme.dat
- Give text entry fields slightly darker background
- Make game title visible in dark mode
I found it hard to understand which text fields are for display only, and which are editable. So, I made their background a bit darker. I hope I haven't missed any.
Screenshots:
=> Theme usabulity tweaks

singularity/code/stats.py
The numbers can get very long during the end game, so it's better to have thousand/million/billion separators.
=> Add separators to numbers on statistics screen

docs/devel/data_files.rst, singularity/code/g.py, singularity/code/graphics/widget.py, singularity/code/polib.py, singularity/code/pycompat.py
There are small typos in:
- docs/devel/data_files.rst
- singularity/code/g.py
- singularity/code/graphics/widget.py
- singularity/code/polib.py
- singularity/code/pycompat.py
Fixes:
- Should read `contains` rather than `contans`.
- Should read `compatibility` rather than `compatiability`.
- Should read `instantiated` rather than `instanciated`.
- Should read `separating` rather than `seperating`.
- Should read `tuple` rather than `touple`.
- Should read `propagated` rather than `propogated`.
- Should read `prerequisites` rather than `preequisites`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: Fix a few typos

docs/devel/data_files.rst
There is a small typo in docs/devel/data_files.rst.
Should read `absence` rather than `abence`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, abence -> absence

Changelog.txt, singularity/code/global_hotkeys.py, singularity/code/screens/base.py
Here is a PoC on creating an auto-build feature as requested in #146.  It currently only builds the "best available items on *empty* base slots".  This enables the player to pre-select some choices and have the auto-builder deal with the rest.
Please review this with the following questions in mind:
* Does the basic functionality work? (i.e. can you make it crash or enable you to build items on bases where you should not)
* Does the visible layout seem good? If not, what do you want to change?
* Does the feature work as you would expect it?  If not, what did you find surprising or what could have been presented better? (e.g. should we rename the button text)
* Would you use the feature as it is? 
@sunfall - there is a single dialog at …
=> WIP: Add auto-build feature (#146)
